### ISSUE TITLE
Better support for custom attributes

### ISSUE THREAD

**Issue by AL333Z** [AL333Z/asyncapi-gen#16]
Currently, we're supporting custom attributes with a syntax that is way too inconvenient.
E.g.:
```
            id:
              type: string
              format: uuid
              x-custom-attributes:
                x-protobuf-index:
                  type: integer
                  value: 1
```

Having something like this would be preferable:

```
            id:
              type: string
              format: uuid
              x-protobuf-index: 1
```

This should be done in a generic way (e.g. all the attributes starting with 'x-'..) without polluting the AsyncApi schema, the tricky part is how the infer the right type for the value.
